version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: api
    networks:
      - api
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - api
    networks:
      - api
networks:
  api: